- name: "Change FLV/AVI to MKV in Galicaster config"
  hosts: new
  user: root
  sudo: yes

  tasks:
  - name: Change presenter.flv to .mkv
    lineinfile:
      dest: /etc/galicaster/conf.ini
      regexp: '^file = presenter.flv'
      state: present
      backrefs: yes
      line: 'file = presenter.mkv'

  - name: Change presenter.avi to .mkv
    lineinfile:
      dest: /etc/galicaster/conf.ini
      regexp: '^file = presenter.avi'
      state: present
      backrefs: yes
      line: 'file = presenter.mkv'
    ignore_errors: true

  - name: Check if muxer is present
    shell: grep "flvmux" /etc/galicaster/conf.ini
    register: muxer_present
    ignore_errors: true

  - name: Replace muxer if present
    lineinfile:
      dest: /etc/galicaster/conf.ini
      regexp: '^muxer = flvmux'
      line: 'muxer = matroskamux'
    when: muxer_present.stdout != ""

  - name: Add muxer if not present
    lineinfile:
      dest: /etc/galicaster/conf.ini
      insertafter: '^name = presenter'
      line: 'muxer = matroskamux'
    when: muxer_present.stdout == ""



