- name: "New Galicaster executable"
  hosts: oc-1616
  user: root
  sudo: yes

  vars:
    proxy_env:
      https_proxy: http://media.uct.ac.za:3128
      http_proxy: http://media.uct.ac.za:3128

  tasks:
   - name: "Update usr/bin/galicaster"
     action: template src="templates/galicaster" dest=/usr/bin/galicaster mode=0777
