- name: "OPENCAST-1762: Update galicaster auth"
  hosts: CAs
  user: root
  sudo: yes

  tasks:
  - lineinfile: 
      dest: /etc/galicaster/conf.ini
      state: present
      regexp: 'username ='
      line: 'username = opencast_ca'

  - lineinfile: 
      dest: /etc/galicaster/conf.ini
      state: present
      regexp: 'password ='
      line: 'password = {{ ca_pass }}'

