- name: "Galicaster update with ACT-601"
  hosts: CAs
  user: root
  sudo: yes

  tasks:
    - name: "Remove all instances of flavor = presentation"
      lineinfile: "dest=/etc/galicaster/conf.ini state=absent regexp='^flavor = presentation'"

    - name: "Add presentation to track 3"
      lineinfile: dest=/etc/galicaster/conf.ini
                  insertafter='^file = presentation.avi' 
                  line='flavor = presentation' 
                  state=present

    - name: "Check if there is a presentation2 in config"
      command: grep track4 /etc/galicaster/conf.ini
      register: checkconf
      always_run: True
      ignore_errors: True
      changed_when: False

    - name: "Add presentation2 to track 4"
      lineinfile: dest=/etc/galicaster/conf.ini
                  insertafter='^name = presentation2'
                  line='flavor = presentation2'
                  state=present
      when: checkconf.rc == 0

    - name: "Update Galicaster to latest 2.x branch"
      unarchive: src=/home/ca/files/galicaster-2.0.x.tar.gz dest=/usr/share/galicaster/

    - name: "Update checkpresentations plugin"
      action: template src="templates/checkpresentations.py" dest=/usr/share/galicaster/galicaster/plugins/checkpresentations.py owner=galicaster mode=0644

    - name: "Reboot CA"
      command: /sbin/shutdown -r

    - name: Wait for the CA to finish rebooting
      sudo: no
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
