- name: "OPENCAST-1879: Update galicaster codebase and auth"
  hosts: CAs
  user: root
  sudo: yes

  tasks:
  - include: tasks/galicaster/update-gc2x.yml

  - lineinfile: 
      dest: /etc/galicaster/conf.ini
      state: present
      regexp: 'username ='
      line: 'username = opencast_system_account'

  - lineinfile: 
      dest: /etc/galicaster/conf.ini
      state: present
      regexp: 'password ='
      line: 'password = {{ ca_pass }}'

