- name: "Capture Agent Deployment Playbook"
  hosts: new
  user: root
  sudo: yes

  vars_files:
    - vars/main.yml

  vars:
    proxy_env:
      http_proxy: http://srvslsopc004.uct.ac.za:3128
      https_proxy: https://srvslsopc004.uct.ac.za:3128

  tasks:
    - include: tasks/main.yml
      environment: "{{proxy_env}}"

