- name: "Capture Agent Deployment Playbook"
  hosts: all
  user: root
  sudo: yes

  vars_files:
    - vars/main.yml

  tasks:
    - include: tasks/main.yml
      environment:
        http_proxy: http://devslsmth001.uct.ac.za:3128

