- name: "Capture Agent Deployment Playbook"
  hosts: new
  user: root

  vars_files:
    - vars/main.yml

  vars:
    proxy_env:
      https_proxy: http://media.uct.ac.za:3128
      http_proxy: http://media.uct.ac.za:3128   

  tasks:
    - include: tasks/main.yml
    #  environment: "{{proxy_env}}"
