# VGA2USB installation

- name: "Copy vga2usb debian package"
  copy: src=/data/files/vga2usb-3.30.7.8-ubuntu-4.15.0-38-generic-x86_64-43279-1807.deb dest=/root/vga2usb-latest.deb

- name: "Install vga2usb"
  shell: dpkg -i /root/vga2usb-latest.deb
  ignore_errors: false
