- name: "Add logrotate.conf file"
  action: template src="templates/logrotate.conf" dest=/etc/logrotate.conf  owner=root mode=0644

- cron: name="Daily CA restart" hour="6" minute="30" job="/sbin/reboot" user="root"

- name: "Install ntp"
  apt: name=ntp state=present

- name: "Ammend ntp.conf file"
  action: template src="templates/ntp.conf" dest=/etc/ntp.conf owner=root mode=0644
 
- name: "Restart ntp service"
  service: name=ntp state=restarted
