- name: "Set recordfail timeout"
  lineinfile: dest=/etc/default/grub
              regexp='^GRUB_RECORDFAIL_TIMEOUT'
              insertafter='^GRUB_TIMEOUT'
              line='GRUB_RECORDFAIL_TIMEOUT=0' 
              state=present

- name: "Update grub"
  action: command update-grub

- name: "Update usr/bin/galicaster"
  action: template src="templates/galicaster" dest=/usr/bin/galicaster mode=0777

- name: "Copy fix for Bosch cameras"
  copy: src=/home/ca/files/libgstrtp.so dest=/usr/lib/x86_64-linux-gnu/gstreamer-0.10
