- name: "Set recordfail timeout"
  lineinfile: dest=/etc/default/grub
              regexp='^GRUB_RECORDFAIL_TIMEOUT'
              insertafter='^GRUB_TIMEOUT'
              line='GRUB_RECORDFAIL_TIMEOUT=2' 
              state=present

- name: "Update grub"
  action: command update-grub

- name: "Add gstreamer log"
  action: template src="templates/galicaster" dest=/usr/bin/galicaster owner=galicaster  mode=0644

