- name: "Set recordfail timeout"
  lineinfile: dest=/etc/default/grub
              regexp='^GRUB_RECORDFAIL_TIMEOUT'
              insertafter='^GRUB_TIMEOUT'
              line='GRUB_RECORDFAIL_TIMEOUT=0' 
              state=present

- name: "Update grub"
  action: command update-grub

- name: "Copy fix for Bosch cameras"
  copy: src=/home/ca/files/libgstrtp.so dest=/usr/lib/x86_64-linux-gnu/gstreamer-0.10
  when: ansible_distribution_version == '12.04'

- name: "Adding lecturesight gc plugin"
  action: template src="templates/gc2x/lecturesight.py" dest=/usr/share/galicaster/galicaster/plugins/lecturesight.py owner=galicaster  mode=0644
  when: ansible_distribution_version == '16.04'
