- name: "Set recordfail timeout"
  lineinfile: dest=/etc/default/grub
              regexp='^GRUB_RECORDFAIL_TIMEOUT'
              insertafter='^GRUB_TIMEOUT'
              line='GRUB_RECORDFAIL_TIMEOUT=0' 
              state=present

- name: "checking if ubuntu 18.04"
  shell: lsb_release -r | grep 18.04 
  register: bionic
  ignore_errors: true

- name: "Set fsckifix=yes for 16.04"
  lineinfile: dest=/etc/default/rcS
              regexp='^(.*)FSCKFIX=no(.*)$'
              line='FSCKFIX=yes'
              state=present
  when: bionic.stdout == ""

- name: "Set fsckfix=yes for 18.04"
  lineinfile: dest=/etc/default/grub
              regexp='^GRUB_CMDLINE_LINUX_DEFAULT=(.*)$'
              line='GRUB_CMDLINE_LINUX_DEFAULT="quiet splash fsck.repair=yes"'
              state=present
  when: bionic.stdout != ""

- name: "Update grub"
  action: command update-grub

- name: "Adding lecturesight gc plugin"
  action: template src="templates/lecturesight.py" dest=/usr/share/galicaster/galicaster/plugins/lecturesight.py owner=galicaster  mode=0644

- name: "Set open file limits"
  action: template src=templates/limits.conf dest=/etc/security/limits.conf owner=root mode=0644

- name: "Copy loglimit.pl"
  copy: src=templates/loglimit.pl dest=/usr/bin owner=root mode=777

- name: "Dont look for updates"
  action: template src=templates/10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root mode=0644

- name: "Dont upgrade packages"
  action: template src=templates/20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades owner=root mode=0664

- name: "ffmpeg static"
  copy: src=/data/files/ffmpeg-3.3-static dest=/usr/local/bin/ owner=galicaster mode=777

- name: "ffprobe static"
  copy: src=/data/files/ffprobe-3.3-static dest=/usr/local/bin/ owner=galicaster mode=777

- name: "videomatch.pl"
  action: template src=templates/videomatch.pl dest=/usr/local/bin/videomatch.pl owner=galicaster mode=777
