- name: "Adding checkpresentations plugin file for 12.04"
  action: template src="templates/gc14/checkpresentations.py" dest=/usr/share/galicaster/galicaster/plugins/checkpresentations.py owner=galicaster  mode=0644
  when: ansible_distribution_version == '12.04'

- name: "Adding checkpresentations plugin file for 16.04"
  action: template src="templates/gc2x/checkpresentations.py" dest=/usr/share/galicaster/galicaster/plugins/checkpresentations.py owner=galicaster  mode=0644
  when: ansible_distribution_version == '16.04'

#- name: "Adding emit signal to dispatcher"
#  lineinfile: dest=/usr/share/galicaster/galicaster/core/dispatcher.py regexp="^gobject " state=present insertbefore="restart-preview" line="gobject.signal_new('recording-closed', Dispatcher, gobject.SIGNAL_RUN_LAST, gobject.TYPE_NONE, (gobject.TYPE_PYOBJECT,) )"
#  when: ansible_distribution_version == '12.04' 

#- name: "Always record 2 presentations"
#  replace: dest=/usr/share/galicaster/galicaster/mediapackage/repository.py regexp="mp.getOCCaptureAgentProperty\('capture.device.names'\)"  replace="'defaults'"
#  when: ansible_distribution_version == '12.04'
