- name: "Adding checkpresentations plugin file for 16.04"
  action: template src="templates/checkpresentations.py" dest=/usr/share/galicaster/galicaster/plugins/checkpresentations.py owner=galicaster  mode=0644
