# generic configuration

- name: "Copy autostart-sh file"
  copy: src=./tasks/galicaster/autostart.sh dest=/tmp/

- name: "Change permissions"
  action: command chdir=/tmp/ chmod +x autostart.sh

- name: "run autostart.sh"
  action: command chdir=/tmp/ sudo ./autostart.sh

- name: "copy post_install file"
  copy: src=./tasks/galicaster/post_install.sh dest=/tmp/

- name: "Change permissions"
  action: command chdir=/tmp/ chmod +x post_install.sh

- name: "run post_install file"
  action: command chdir=/tmp/ sudo ./post_install.sh

- name: "Change ownership"
  action: command chown -R galicaster:galicaster /usr/bin/galicaster

- name: "Change permissions"
  action: command chmod 777 /usr/bin/galicaster

- name: "Copy autostart file to capture agent"
  copy: src=./templates/galicaster.desktop dest=/home/galicaster/.config/autostart/


- name: "update conf.ini file"
  action: template src="templates/conf.ini" dest=/etc/galicaster/conf.ini  owner=galicaster mode=0644

- name: "Update usr/bin/galicaster"
  action: template src="templates/galicaster" dest=/usr/bin/galicaster mode=0777

- name: "update conf-dist file"
  action: template src="templates/conf-dist.ini" dest=/usr/share/galicaster/conf-dist.ini  owner=galicaster mode=0644
