#- name: "Creating the config file"
#  action: command chdir=/etc/ sudo mkdir galicaster

- name: "add conf.ini file"
  action: template src="templates/conf.ini" dest=/etc/galicaster/conf.ini owner=root  mode=0644
  
- name: "Creating the conf-dist file"
  action: template src="templates/conf-dist.ini" dest=/usr/share/galicaster/conf-dist.ini owner=root  mode=0644


- name: "Copy autostart-sh file"
  copy: src=/etc/ansible/tasks/galicaster/autostart.sh dest=/tmp/

- name: "run autostart.sh"
  action: command chdir=/tmp/ sudo ./autostart.sh

#- name: "create autostart file"
#  action: command sudo mkdir autostart chdir=~/.config/ owner=root

#- name: "Set Galicaster to load on boot"
#  copy: src=/usr/share/galicaster/docs/autostart/galicaster.desktop  dest=~/.config/autostart/ owner=root mode=0644
