- name: "Creating the config file"
  action: command chdir=/etc/ sudo mkdir -p galicaster

- name: "add conf.ini file"
  action: template src="templates/conf.ini" dest=/etc/galicaster/conf.ini  owner=galicaster mode=0644
  
- name: "Creating the conf-dist file"
  action: template src="templates/conf-dist.ini" dest=/usr/share/galicaster/conf-dist.ini owner=galicaster  mode=0644


- name: "Copy autostart-sh file"
  copy: src=/etc/ansible/tasks/galicaster/autostart.sh dest=/tmp/

- name: "run autostart.sh"
  action: command chdir=/tmp/ sudo ./autostart.sh


- name: "copy post_install file"
  copy: src=/etc/ansible/tasks/galicaster/post_install.sh dest=/tmp/

- name: "run post_install file"
  action: command chdir=/tmp/ sudo ./post_install.sh
