- name: "Get latest galicaster build"
  git: repo=https://bitbucket.org/cilt/galicaster-1.4.git dest=/tmp/galicaster

- name: "Delete folder"
  action: command chdir=/usr/share/ sudo rm -rf galicaster

- name: "Move folder"
  action: command chdir=/tmp sudo mv -f galicaster /usr/share/

- name: "Install galicaster"
  action: command chdir=/usr/share/galicaster/ python setup.py install
