# 12.04 configuration

- name: "Download latest galicaster build"
  copy: src=/home/ca/files/galicaster-1.4-uct.tar.gz dest=/tmp/
  when: ansible_distribution_version == '12.04'

- name: "Unzip galicaster update"
  action: command tar xvf /tmp/galicaster-1.4-uct.tar.gz chdir=/tmp/
  when: ansible_distribution_version == '12.04'

- name: "Delete folder"
  action: command chdir=/usr/share/ sudo rm -rf galicaster
  when: ansible_distribution_version == '12.04'

- name: "Move folder"
  action: command chdir=/tmp sudo mv -f galicaster-1.4-uct /usr/share/galicaster/
  when: ansible_distribution_version == '12.04'

- name: "Install galicaster"
  action: command chdir=/usr/share/galicaster/ python setup.py install
  when: ansible_distribution_version == '12.04'

# 16.04 configuration

- name: "Copy galicaster repo script"
  copy: src=/home/ca/ca_deployment/tasks/galicaster/install_repo.sh dest=/root/
  when: ansible_distribution_version == '16.04'

- name: "Add galicaster 2 repo"
  shell: bash /root/install_repo.sh
  when: ansible_distribution_version == '16.04'
#  environment: "{{proxy_env}}"

- name: "Update repository"
  apt: update_cache=yes
  when: ansible_distribution_version == '16.04'
#  environment: "{{proxy_env}}"

- name: "Install galicaster 2.0.x"
  apt: name=galicaster state=present force=yes
  when: ansible_distribution_version == '16.04'
#  #environment: "{{proxy_env}}"
