- name: "Copy galicaster repo script"
  copy: src=/home/ca/ca_deployment/tasks/galicaster/install_repo.sh dest=/root/

- name: "Add galicaster 2 repo"
  shell: bash /root/install_repo.sh
  environment: "{{proxy_env}}"

- name: "Update repository"
  apt: update_cache=yes
  environment: "{{proxy_env}}"

- name: "Remove /usr/share/galicaster"
  shell: rm -rf /usr/share/galicaster

- name: "Install galicaster 2.0.x"
  apt: name=galicaster state=present force=yes
  environment: "{{proxy_env}}"

- name: "Update Galicaster to latest 2.x branch"
  unarchive: src=/home/ca/files/galicaster-2.0.x.tar.gz dest=/usr/share/galicaster/  

- name: "Change ownership of /usr/share/galicaster"
  command: chown -R galicaster:galicaster /usr/share/galicaster
