- name: "Remove /usr/share/galicaster"
  shell: rm -rf /usr/share/galicaster

- name: "Create galicaster folder"
  file: path=/usr/share/galicaster state=directory owner=galicaster group=galicaster

- name: "Update Galicaster to latest 2.x branch"
  unarchive: src=/home/ca/files/galicaster-2.0.x.tar.gz dest=/usr/share/galicaster/  

- name: "Change ownership of /usr/share/galicaster"
  command: chown -R galicaster:galicaster /usr/share/galicaster

- name: "Create /etc/galicaster"
  file: path=/etc/galicaster state=directory owner=galicaster group=galicaster

- name: "Update usr/bin/galicaster"
  action: template src="templates/galicaster" dest=/usr/bin/galicaster mode=0777

- name: "Change ownership of /usr/bin/galicaster"
  command: chown galicaster:galicaster /usr/bin/galicaster

- name: "update conf-dist file"
  action: template src="templates/conf-dist.ini" dest=/usr/share/galicaster/conf-dist.ini  owner=galicaster mode=0644

- name: "Add lecturesight plugin"
  action: template src="templates/lecturesight.py" dest=/usr/share/galicaster/galicaster/plugins/lecturesight.py owner=galicaster mode=0644

- name: "Add checkpresentations plugin"
  action: template src="templates/checkpresentations.py" dest=/usr/share/galicaster/galicaster/plugins/checkpresentations.py owner=galicaster mode=0644

- name: "install galicaster"
  command: python /usr/share/galicaster/setup.py install

- name: "change ownership of /usr/share/galicaster"
  file: path=/usr/share/galicaster state=directory owner=galicaster group=galicaster mode=0775 recurse=yes
