
- name: "Install galicaster dependencies"
  action: apt pkg=${item} state=installed force=yes
  with_items: ${galicaster_install.dependencies}


- name: "Installing icalendar from PIP" 
  action: command pip install --proxy=http://arabica.cet.uct.ac.za:8999 icalendar==2.2




