- name: "Install missing gstreamer1.x binaries for 16.04"
  apt: name={{item}} state=present force=yes
  with_items:
    - python-gst-1.0
    #- libgstreamer1.0*
    - python-pip
    - python-dbus
    - python-setuptools
    - python-pycurl
    - v4l-conf
    - v4l-utils
    - python-dateutil
    - ivtv-utils
    - python-bottle
    - python-glade2
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-bad-faad
    - gstreamer1.0-plugins-bad-videoparsers

# generic configuration

- name: "Download icalendar" 
  copy: src=/home/ca/files/icalendar-2.2.tar.gz dest=/tmp/

- name: "Extract icalendar"
  action: command tar xvf /tmp/icalendar-2.2.tar.gz chdir=/tmp/

- name: "Install icalender"
  action: command python setup.py install chdir=/tmp/icalendar-2.2/
