# 12.04 configuration

- name: "Install galicaster dependencies for 12.04"
  apt: pkg={{item}} state=installed force=yes
  with_items:
    - python
    - python-gtk2
    - python-gst0.10
    - libgtk2.0-0
    - libgstreamer0.10-0
    - gstreamer0.10-ffmpeg
    - gstreamer0.10-alsa
    - gstreamer0.10-plugins-bad
    - gstreamer0.10-plugins-bad-multiverse
    - gstreamer0.10-plugins-base
    - gstreamer0.10-plugins-base-apps
    - gstreamer0.10-plugins-good
    - gstreamer0.10-plugins-ugly
    - python-pip
    - python-setuptools
    - python-pycurl
    - v4l-conf
    - v4l-utils
    - python-dateutil
    - ivtv-utils
    - python-bottle
    - python-glade2
  when: ansible_distribution_version == '12.04'

# 16.04 configuration

- name: "Install missing gstreamer1.x binaries for 16.04"
  apt: name={{item}} state=present force=yes
  with_items:
    - python-gst-1.0
    #- libgstreamer1.0*
    - python-pip
    - python-setuptools
    - python-pycurl
    - v4l-conf
    - v4l-utils
    - python-dateutil
    - ivtv-utils
    - python-bottle
    - python-glade2
  when: ansible_distribution_version == '16.04'

# generic configuration

- name: "Download icalendar" 
  copy: src=/home/ca/files/icalendar-2.2.tar.gz dest=/tmp/

- name: "Extract icalendar"
  action: command tar xvf /tmp/icalendar-2.2.tar.gz chdir=/tmp/

- name: "Install icalender"
  action: command python setup.py install chdir=/tmp/icalendar-2.2/
