- name: "Install cuda for 16.04"
  apt: name={{item}} state=present force=yes
  with_items:
    - nvidia-cuda-dev 
    - nvidia-cuda-doc 
    - nvidia-cuda-gdb 
    - nvidia-cuda-toolkit
    - libcuda1-367
