- name: "install cuda"
  copy: src=/home/ca/files/ dest=/tmp/

- name: "install cuda"
  action: command /usr/bin/dpkg --install /tmp/cuda-7.0.28.deb

#- name: "Get opencl"
#  copy: src=/home/ca/files/opencl.tgz dest=/tmp/opencl.tgz

#- name: "Untar and uncompress OpenCL application"
#  action: command tar xvf /tmp/opencl.tgz chdir=/tmp/

