- name: "install cuda"
  get_url: url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_5.5-0_amd64.deb dest=/tmp/cuda.deb

- name: "install cuda"
  action: command /usr/bin/dpkg --install /tmp/cuda.deb

- name: "Copy opencl_download.sh"
  copy: src=/etc/ansible/tasks/lecturesight/opencl_download.sh dest=/tmp/

- name: "Run opencl_download.sh"
  action: command chdir=/tmp/ /tmp/opencl_download.sh

#- name: "install OpenCL"
#  get_url: url=http://registrationcenter.intel.com/irc_nas/3555/intel_sdk_for_ocl_applications_xe_2013_r2_sdk_3.1.1.11385_x64.tgz dest=/tmp/opencl.tgz

- name: "Untar and uncompress OpenCL application"
  action: command tar xvf /tmp/opencl.tgz chdir=/tmp/

