- name: "Create Lecturesight directory if not exists"
  action: command mkdir -p /opt/ls

- name: "Untar and uncompress LS update file"
  unarchive: src=/data/files/lsuct-latest.tgz dest=/opt/ls

- name: "Copy lecturesight start script"
  copy: src=lecturesight dest=/usr/bin/

- name: "Make executable"
  file: path=/usr/bin/lecturesight state=touch mode="u+rwx,g+rx,o+rx"
