- name: "Create Lecturesight directory if not exists"
  action: command mkdir -p /opt/ls
  when: ls.stat.exists == False

- name: "Untar and uncompress LS update file"
  unarchive: src=/home/ca/files/lsuct-latest.tgz dest=/opt/ls
