- name: "make Java folder"
  action: command mkdir -p /temp

- name: Download JDK (Ubuntu)
  unarchive: src=/home/ca/files/jdk-7u79-linux-x64.tar.gz dest=/temp

- name: "Add system variables to system path"
  action: template src="templates/profile" dest=/etc/profile owner=galicaster  mode=0644

- name: Set java link
  action: command update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.7.0_79/bin/java 1

- name: Set javaws link
  action: command update-alternatives --install /usr/bin/javaws javaws /usr/lib/jvm/jdk1.7.0_79/bin/javaws 1

- name: Set Ownership and permission
  action: command chmod a+x /usr/bin/java && sudo chown -R root:root /usr/lib/jvm/jdk1.7.0_79/

- name: Set java jre to default
  action: command update-alternatives --set java /usr/lib/jvm/jdk1.7.0_79/bin/java

- name: Remove JDK tarbal
  file: path=/temp/jdk-7u79-linux-x64.tar.gz state=absent
