- name: "Install java dependencies"
  apt: name={{item}} state=present force=yes
  with_items:
    - fastjar
    - jarwrapper
    - realpath
    - libjpeg-turbo8-dev 
    - ant 
    - libv4l-dev 
    - libjpeg-dev
    - libdbus-glib-1-dev

- name: "Copy libvl4j binaries"
  copy: src=/home/ca/files/v4l4j/ dest=/root/

- name: "Install libvl4j binaries"
  shell: dpkg -i /root/libv*.deb 


# generic configuration

- name: "Configure webcam symlink"
  action: template src="templates/83-duplicate_devs.rules" dest=/etc/udev/rules.d/ owner=root  mode=0644

- name: "Setting lecturesight startup 1"
  lineinfile: "dest=/etc/sudoers line='galicaster ALL=(ALL) NOPASSWD: /opt/ls/start_lecturesight.sh'"

- name: "create autostart folder"
  copy: src=/home/ca/ca_deployment/tasks/lecturesight/autostart.sh dest=/root/

- name: "run autostart script"
  action: command bash /root/autostart.sh

- name: "Set lecturesight autostart"
  action: template src="templates/lecturesight.desktop" dest=/home/galicaster/.config/autostart/ owner=root mode=0755

- name: "Set cron job to stop lecturesight at 5:30am"
  cron: name="stop lecturesight" minute="30" hour="5" job="/opt/ls/stop_lecturesight.sh"
