- name: "Download Datapath driver"
  copy: src=/usr/share/ansible/etc/tasks/datapath/download_datapath.sh dest=/tmp/

- name: "Change permissions"
  action: command chdir=/tmp/ chmod +x /tmp/download_datapath.sh

- name: "Run script"
  action: command chdir=/tmp/ ./download_datapath.sh

- name: "Extract driver"
  action: command tar -zxvf /tmp/VisionInstall-7.6.0.124.tar.gz chdir=/tmp/

- name: "Install Datapath driver"
  shell: chdir=/tmp/ yes "Y" | ./scripts/install.kernel 


 
