# generic configuration

- name: "Make a folder in home directory"
  action: command chdir=/home/galicaster sudo mkdir -p datapath

- name: "Copy datapath driver archive"
  copy: src=/home/ca/files/datapath.tar.gz dest=/home/galicaster/

- name: "Extract driver"
  action: command tar xvf /home/galicaster/datapath.tar.gz chdir=/home/galicaster/

- name: "Install Datapath driver"
  shell: chdir=/home/galicaster/datapath yes "Y" | ./scripts/install.kernel

- name: "Copy rgb133.conf"
  copy: src=/home/ca/ca_deployment/templates/rgb133.conf dest=/etc/modprobe.d/

- name: "Remove tar file"
  action: command chdir=/home/galicaster/ sudo rm -r datapath.tar.gz
