# generic configuration

- name: "Make visionlc dir"
  shell: mkdir -p /home/galicaster/visionlc

- name: "Extract visionlc driver"
  unarchive: src=/data/files/visionlc.tar.gz dest=/home/galicaster/ owner=root group=root

- name: "Install VisionLC driver"
  shell: chdir=/home/galicaster/visionlc yes "Y" | ./scripts/install.kernel

- name: "Copy rgb200.conf"
  action: template src=templates/rgb200.conf dest=/etc/modprobe.d/
