# generic configuration

- name: "Download blackmagic file"
  copy: src=/home/ca/files/desktopvideo_10.6.8a2_amd64.deb dest=/tmp/blackmagic.deb

- name: "Install Blackmagic driver"
  action: command /usr/bin/dpkg --install /tmp/blackmagic.deb

- name: "modprobe"
  command: /sbin/modprobe blackmagic
  when: ansible_distribution_version == '12.04'

 
