- name: "Copy blackmagic_download script"
  copy: src=./tasks/blackmagic/blackmagic_download.sh dest=/tmp/

- name: "Change permissions on blackmagic_download.sh"
  action: command chmod +x /tmp/blackmagic_download.sh

- name: "Run script"
  action: command chdir=/tmp/ /tmp/blackmagic_download.sh

- name: "Install Blackmagic driver"
  action: command /usr/bin/dpkg --install /tmp/blackmagic.deb

- name: "modprobe"
  command: /sbin/modprobe blackmagic

 
