- name: "Copy blackmagic_download script"
  copy: src=/etc/ansible/tasks/blackmagic/blackmagic_download.sh dest=/tmp/

- name: "Run script"
  action: command chdir=/tmp/ /tmp/blackmagic_download.sh

- name: "Install Blackmagic driver"
  action: command /usr/bin/dpkg --install /tmp/desktopvideo-9.8-amd64.deb

- name: "modprobe"
  command: /sbin/modprobe blackmagic

 
