# generic configuration

- name: "Download blackmagic file"
  copy: src=/data/files/blackmagic.deb dest=/tmp/blackmagic.deb

- name: "Install Blackmagic driver"
  action: command /usr/bin/dpkg --install /tmp/blackmagic.deb 
