#! /bin/bash

# Audio monitoring
# configure darkice.cfg from darkice.cfg-template using Galicaster hostname and audio config

logger "Audio monitoring: darkice started"

echo ""
echo "########### Audio monitoring started: press Ctrl-C to cancel ###########"
echo ""

GC=/etc/galicaster
CAPTURE_AGENT=`grep ^hostname $GC/conf.ini | sed "s/ //g" | awk -F = '{print $2}'`
PULSE_SRC=`grep ^location $GC/conf.ini | grep alsa | sed "s/ //g" | awk -F = '{print $2}'`
sed -e "s/CAPTURE_AGENT/$CAPTURE_AGENT/g" -e "s/PULSE_SRC/$PULSE_SRC/g" < $GC/darkice.cfg-template > $GC/darkice.cfg
killall -q darkice 
/usr/bin/darkice -c $GC/darkice.cfg 

